sample_payload: 'sample_payload.json'
EXPT_DIR : "./log"
LOG_DIR : "./log"
DATA_DIR : "./data"
WEIGHTS_DIR : "./weights"
exp_name: "cityscape"

### TRAIN FUNCTION ARGS ###
epochs: 2
batch_size: 16
lr: 0.01
num_classes: 10
