sample_payload: 'sample_payload.json'
EXPT_DIR : "./log"
LOG_DIR : "./log"
DATA_DIR : "./data"
WEIGHTS_DIR : "./weights"
exp_name: "cifar-10"
weightsclear: True

### TRAIN FUNCTION ARGS ###
onprem: True
train_epochs: 25
batch_size: 16
lr: 0.00001
wtd: 0.0001
momentum: 0.9